### PR TITLE
add libav tools

### PR DESCRIPTION
**Pull request by alavieille**

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by nicolasThal** [comment]
:+1:

**Comment by nicolasThal** [comment]
You should put the libav-tools installation in the php role

**Comment by nicolasThal** [comment]
As it is used only if the php project is  installed on the server

**Comment by alavieille** [comment]
@nicolasThal

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
